version: '3.9'

networks:
  portfolio:
    driver: "bridge"

services:

#PHP-FPM service
  app:
    build: .
    container_name: portfolio_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/portfolio
    depends_on:
      - db

    volumes:
      - ./:/var/www/portfolio
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - portfolio

  #NGINX service
  webserver: 
    image: nginx
    container_name: webserver
    restart: always
    # tty: true
    
    ports:
      - '8088:80'
      - '8143:443'
      - "3001:3001"
    
    volumes:
      - ./:/var/www/portfolio
      - ./docker-files/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    
    networks:
      - portfolio
      
  db:
    platform: linux/x86_64
    container_name: portfolio_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    restart: always
    # tty: true
    ports:
      -  "33060:3306"

    volumes:
      -  ./storage/dbdata:/var/lib/mysql
      -  ./docker-files/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - portfolio

# Adminer service
  adminer:
    container_name: portfolio_adminer
    image: adminer:latest
    restart: always
    ports:
      - "8089:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - portfolio

